// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotState.proto

package eu.rockin.roah_rsbb_msgs;

public final class RobotStateProtos {
  private RobotStateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RobotStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roah_rsbb_msgs.RobotState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.Time getTime();
    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getTimeOrBuilder();

    /**
     * <code>required uint32 messages_saved = 2;</code>
     *
     * <pre>
     * Number of messages saved by the offline data saver
     * </pre>
     */
    boolean hasMessagesSaved();
    /**
     * <code>required uint32 messages_saved = 2;</code>
     *
     * <pre>
     * Number of messages saved by the offline data saver
     * </pre>
     */
    int getMessagesSaved();
  }
  /**
   * Protobuf type {@code roah_rsbb_msgs.RobotState}
   */
  public static final class RobotState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:roah_rsbb_msgs.RobotState)
      RobotStateOrBuilder {
    // Use RobotState.newBuilder() to construct.
    private RobotState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RobotState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RobotState defaultInstance;
    public static RobotState getDefaultInstance() {
      return defaultInstance;
    }

    public RobotState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RobotState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(eu.rockin.roah_rsbb_msgs.TimeProtos.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messagesSaved_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.rockin.roah_rsbb_msgs.RobotStateProtos.internal_static_roah_rsbb_msgs_RobotState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.rockin.roah_rsbb_msgs.RobotStateProtos.internal_static_roah_rsbb_msgs_RobotState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.class, eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.Builder.class);
    }

    public static com.google.protobuf.Parser<RobotState> PARSER =
        new com.google.protobuf.AbstractParser<RobotState>() {
      public RobotState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RobotState> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code roah_rsbb_msgs.RobotState.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 6666;</code>
       */
      COMP_ID(0, 6666),
      /**
       * <code>MSG_TYPE = 40;</code>
       */
      MSG_TYPE(1, 40),
      ;

      /**
       * <code>COMP_ID = 6666;</code>
       */
      public static final int COMP_ID_VALUE = 6666;
      /**
       * <code>MSG_TYPE = 40;</code>
       */
      public static final int MSG_TYPE_VALUE = 40;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 6666: return COMP_ID;
          case 40: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:roah_rsbb_msgs.RobotState.CompType)
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private eu.rockin.roah_rsbb_msgs.TimeProtos.Time time_;
    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getTime() {
      return time_;
    }
    /**
     * <code>required .roah_rsbb_msgs.Time time = 1;</code>
     *
     * <pre>
     * UTC time, to check clock synchronization
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getTimeOrBuilder() {
      return time_;
    }

    public static final int MESSAGES_SAVED_FIELD_NUMBER = 2;
    private int messagesSaved_;
    /**
     * <code>required uint32 messages_saved = 2;</code>
     *
     * <pre>
     * Number of messages saved by the offline data saver
     * </pre>
     */
    public boolean hasMessagesSaved() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 messages_saved = 2;</code>
     *
     * <pre>
     * Number of messages saved by the offline data saver
     * </pre>
     */
    public int getMessagesSaved() {
      return messagesSaved_;
    }

    private void initFields() {
      time_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      messagesSaved_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessagesSaved()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, messagesSaved_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, messagesSaved_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code roah_rsbb_msgs.RobotState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roah_rsbb_msgs.RobotState)
        eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.rockin.roah_rsbb_msgs.RobotStateProtos.internal_static_roah_rsbb_msgs_RobotState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.rockin.roah_rsbb_msgs.RobotStateProtos.internal_static_roah_rsbb_msgs_RobotState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.class, eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.Builder.class);
      }

      // Construct using eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (timeBuilder_ == null) {
          time_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
        } else {
          timeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        messagesSaved_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.rockin.roah_rsbb_msgs.RobotStateProtos.internal_static_roah_rsbb_msgs_RobotState_descriptor;
      }

      public eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState getDefaultInstanceForType() {
        return eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.getDefaultInstance();
      }

      public eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState build() {
        eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState buildPartial() {
        eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState result = new eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messagesSaved_ = messagesSaved_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState) {
          return mergeFrom((eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState other) {
        if (other == eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState.getDefaultInstance()) return this;
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        if (other.hasMessagesSaved()) {
          setMessagesSaved(other.getMessagesSaved());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        if (!hasMessagesSaved()) {
          
          return false;
        }
        if (!getTime().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.rockin.roah_rsbb_msgs.RobotStateProtos.RobotState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private eu.rockin.roah_rsbb_msgs.TimeProtos.Time time_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> timeBuilder_;
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getTime() {
        if (timeBuilder_ == null) {
          return time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public Builder setTime(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public Builder setTime(
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public Builder mergeTime(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              time_ != eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance()) {
            time_ =
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
          onChanged();
        } else {
          timeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder getTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_;
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time time = 1;</code>
       *
       * <pre>
       * UTC time, to check clock synchronization
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private int messagesSaved_ ;
      /**
       * <code>required uint32 messages_saved = 2;</code>
       *
       * <pre>
       * Number of messages saved by the offline data saver
       * </pre>
       */
      public boolean hasMessagesSaved() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 messages_saved = 2;</code>
       *
       * <pre>
       * Number of messages saved by the offline data saver
       * </pre>
       */
      public int getMessagesSaved() {
        return messagesSaved_;
      }
      /**
       * <code>required uint32 messages_saved = 2;</code>
       *
       * <pre>
       * Number of messages saved by the offline data saver
       * </pre>
       */
      public Builder setMessagesSaved(int value) {
        bitField0_ |= 0x00000002;
        messagesSaved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 messages_saved = 2;</code>
       *
       * <pre>
       * Number of messages saved by the offline data saver
       * </pre>
       */
      public Builder clearMessagesSaved() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messagesSaved_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:roah_rsbb_msgs.RobotState)
    }

    static {
      defaultInstance = new RobotState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:roah_rsbb_msgs.RobotState)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roah_rsbb_msgs_RobotState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_roah_rsbb_msgs_RobotState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RobotState.proto\022\016roah_rsbb_msgs\032\nTime" +
      ".proto\"p\n\nRobotState\022\"\n\004time\030\001 \002(\0132\024.roa" +
      "h_rsbb_msgs.Time\022\026\n\016messages_saved\030\002 \002(\r" +
      "\"&\n\010CompType\022\014\n\007COMP_ID\020\2124\022\014\n\010MSG_TYPE\020(" +
      "B,\n\030eu.rockin.roah_rsbb_msgsB\020RobotState" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          eu.rockin.roah_rsbb_msgs.TimeProtos.getDescriptor(),
        }, assigner);
    internal_static_roah_rsbb_msgs_RobotState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_roah_rsbb_msgs_RobotState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_roah_rsbb_msgs_RobotState_descriptor,
        new java.lang.String[] { "Time", "MessagesSaved", });
    eu.rockin.roah_rsbb_msgs.TimeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
