// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TabletBeacon.proto

package eu.rockin.roah_rsbb_msgs;

public final class TabletBeaconProtos {
  private TabletBeaconProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TabletBeaconOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roah_rsbb_msgs.TabletBeacon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    boolean hasLastCall();
    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastCall();
    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastCallOrBuilder();

    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    boolean hasLastPos();
    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastPos();
    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastPosOrBuilder();

    /**
     * <code>required double x = 3;</code>
     *
     * <pre>
     * Coordinate X
     * </pre>
     */
    boolean hasX();
    /**
     * <code>required double x = 3;</code>
     *
     * <pre>
     * Coordinate X
     * </pre>
     */
    double getX();

    /**
     * <code>required double y = 4;</code>
     *
     * <pre>
     * Coordinate Y
     * </pre>
     */
    boolean hasY();
    /**
     * <code>required double y = 4;</code>
     *
     * <pre>
     * Coordinate Y
     * </pre>
     */
    double getY();
  }
  /**
   * Protobuf type {@code roah_rsbb_msgs.TabletBeacon}
   */
  public static final class TabletBeacon extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:roah_rsbb_msgs.TabletBeacon)
      TabletBeaconOrBuilder {
    // Use TabletBeacon.newBuilder() to construct.
    private TabletBeacon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TabletBeacon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TabletBeacon defaultInstance;
    public static TabletBeacon getDefaultInstance() {
      return defaultInstance;
    }

    public TabletBeacon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TabletBeacon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = lastCall_.toBuilder();
              }
              lastCall_ = input.readMessage(eu.rockin.roah_rsbb_msgs.TimeProtos.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastCall_);
                lastCall_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = lastPos_.toBuilder();
              }
              lastPos_ = input.readMessage(eu.rockin.roah_rsbb_msgs.TimeProtos.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastPos_);
                lastPos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              x_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              y_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.internal_static_roah_rsbb_msgs_TabletBeacon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.internal_static_roah_rsbb_msgs_TabletBeacon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.class, eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.Builder.class);
    }

    public static com.google.protobuf.Parser<TabletBeacon> PARSER =
        new com.google.protobuf.AbstractParser<TabletBeacon>() {
      public TabletBeacon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TabletBeacon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TabletBeacon> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code roah_rsbb_msgs.TabletBeacon.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 6666;</code>
       */
      COMP_ID(0, 6666),
      /**
       * <code>MSG_TYPE = 35;</code>
       */
      MSG_TYPE(1, 35),
      ;

      /**
       * <code>COMP_ID = 6666;</code>
       */
      public static final int COMP_ID_VALUE = 6666;
      /**
       * <code>MSG_TYPE = 35;</code>
       */
      public static final int MSG_TYPE_VALUE = 35;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 6666: return COMP_ID;
          case 35: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:roah_rsbb_msgs.TabletBeacon.CompType)
    }

    private int bitField0_;
    public static final int LAST_CALL_FIELD_NUMBER = 1;
    private eu.rockin.roah_rsbb_msgs.TimeProtos.Time lastCall_;
    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    public boolean hasLastCall() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastCall() {
      return lastCall_;
    }
    /**
     * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
     *
     * <pre>
     * UTC time, time when the last call message via button is transmitted
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastCallOrBuilder() {
      return lastCall_;
    }

    public static final int LAST_POS_FIELD_NUMBER = 2;
    private eu.rockin.roah_rsbb_msgs.TimeProtos.Time lastPos_;
    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    public boolean hasLastPos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastPos() {
      return lastPos_;
    }
    /**
     * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
     *
     * <pre>
     * UTC time, time when the last call message via image is transmitted
     * </pre>
     */
    public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastPosOrBuilder() {
      return lastPos_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private double x_;
    /**
     * <code>required double x = 3;</code>
     *
     * <pre>
     * Coordinate X
     * </pre>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double x = 3;</code>
     *
     * <pre>
     * Coordinate X
     * </pre>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private double y_;
    /**
     * <code>required double y = 4;</code>
     *
     * <pre>
     * Coordinate Y
     * </pre>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double y = 4;</code>
     *
     * <pre>
     * Coordinate Y
     * </pre>
     */
    public double getY() {
      return y_;
    }

    private void initFields() {
      lastCall_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      lastPos_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      x_ = 0D;
      y_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLastCall()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastPos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLastCall().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLastPos().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, lastCall_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, lastPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lastCall_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, lastPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code roah_rsbb_msgs.TabletBeacon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roah_rsbb_msgs.TabletBeacon)
        eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeaconOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.internal_static_roah_rsbb_msgs_TabletBeacon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.internal_static_roah_rsbb_msgs_TabletBeacon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.class, eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.Builder.class);
      }

      // Construct using eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLastCallFieldBuilder();
          getLastPosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (lastCallBuilder_ == null) {
          lastCall_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
        } else {
          lastCallBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (lastPosBuilder_ == null) {
          lastPos_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
        } else {
          lastPosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.internal_static_roah_rsbb_msgs_TabletBeacon_descriptor;
      }

      public eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon getDefaultInstanceForType() {
        return eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.getDefaultInstance();
      }

      public eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon build() {
        eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon buildPartial() {
        eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon result = new eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (lastCallBuilder_ == null) {
          result.lastCall_ = lastCall_;
        } else {
          result.lastCall_ = lastCallBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (lastPosBuilder_ == null) {
          result.lastPos_ = lastPos_;
        } else {
          result.lastPos_ = lastPosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon) {
          return mergeFrom((eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon other) {
        if (other == eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon.getDefaultInstance()) return this;
        if (other.hasLastCall()) {
          mergeLastCall(other.getLastCall());
        }
        if (other.hasLastPos()) {
          mergeLastPos(other.getLastPos());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLastCall()) {
          
          return false;
        }
        if (!hasLastPos()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!getLastCall().isInitialized()) {
          
          return false;
        }
        if (!getLastPos().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.rockin.roah_rsbb_msgs.TabletBeaconProtos.TabletBeacon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private eu.rockin.roah_rsbb_msgs.TimeProtos.Time lastCall_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> lastCallBuilder_;
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public boolean hasLastCall() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastCall() {
        if (lastCallBuilder_ == null) {
          return lastCall_;
        } else {
          return lastCallBuilder_.getMessage();
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public Builder setLastCall(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (lastCallBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastCall_ = value;
          onChanged();
        } else {
          lastCallBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public Builder setLastCall(
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder builderForValue) {
        if (lastCallBuilder_ == null) {
          lastCall_ = builderForValue.build();
          onChanged();
        } else {
          lastCallBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public Builder mergeLastCall(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (lastCallBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              lastCall_ != eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance()) {
            lastCall_ =
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.newBuilder(lastCall_).mergeFrom(value).buildPartial();
          } else {
            lastCall_ = value;
          }
          onChanged();
        } else {
          lastCallBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public Builder clearLastCall() {
        if (lastCallBuilder_ == null) {
          lastCall_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
          onChanged();
        } else {
          lastCallBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder getLastCallBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLastCallFieldBuilder().getBuilder();
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastCallOrBuilder() {
        if (lastCallBuilder_ != null) {
          return lastCallBuilder_.getMessageOrBuilder();
        } else {
          return lastCall_;
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_call = 1;</code>
       *
       * <pre>
       * UTC time, time when the last call message via button is transmitted
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> 
          getLastCallFieldBuilder() {
        if (lastCallBuilder_ == null) {
          lastCallBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder>(
                  getLastCall(),
                  getParentForChildren(),
                  isClean());
          lastCall_ = null;
        }
        return lastCallBuilder_;
      }

      private eu.rockin.roah_rsbb_msgs.TimeProtos.Time lastPos_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> lastPosBuilder_;
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public boolean hasLastPos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time getLastPos() {
        if (lastPosBuilder_ == null) {
          return lastPos_;
        } else {
          return lastPosBuilder_.getMessage();
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public Builder setLastPos(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (lastPosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastPos_ = value;
          onChanged();
        } else {
          lastPosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public Builder setLastPos(
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder builderForValue) {
        if (lastPosBuilder_ == null) {
          lastPos_ = builderForValue.build();
          onChanged();
        } else {
          lastPosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public Builder mergeLastPos(eu.rockin.roah_rsbb_msgs.TimeProtos.Time value) {
        if (lastPosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              lastPos_ != eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance()) {
            lastPos_ =
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time.newBuilder(lastPos_).mergeFrom(value).buildPartial();
          } else {
            lastPos_ = value;
          }
          onChanged();
        } else {
          lastPosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public Builder clearLastPos() {
        if (lastPosBuilder_ == null) {
          lastPos_ = eu.rockin.roah_rsbb_msgs.TimeProtos.Time.getDefaultInstance();
          onChanged();
        } else {
          lastPosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder getLastPosBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLastPosFieldBuilder().getBuilder();
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      public eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder getLastPosOrBuilder() {
        if (lastPosBuilder_ != null) {
          return lastPosBuilder_.getMessageOrBuilder();
        } else {
          return lastPos_;
        }
      }
      /**
       * <code>required .roah_rsbb_msgs.Time last_pos = 2;</code>
       *
       * <pre>
       * UTC time, time when the last call message via image is transmitted
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder> 
          getLastPosFieldBuilder() {
        if (lastPosBuilder_ == null) {
          lastPosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.rockin.roah_rsbb_msgs.TimeProtos.Time, eu.rockin.roah_rsbb_msgs.TimeProtos.Time.Builder, eu.rockin.roah_rsbb_msgs.TimeProtos.TimeOrBuilder>(
                  getLastPos(),
                  getParentForChildren(),
                  isClean());
          lastPos_ = null;
        }
        return lastPosBuilder_;
      }

      private double x_ ;
      /**
       * <code>required double x = 3;</code>
       *
       * <pre>
       * Coordinate X
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double x = 3;</code>
       *
       * <pre>
       * Coordinate X
       * </pre>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>required double x = 3;</code>
       *
       * <pre>
       * Coordinate X
       * </pre>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double x = 3;</code>
       *
       * <pre>
       * Coordinate X
       * </pre>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>required double y = 4;</code>
       *
       * <pre>
       * Coordinate Y
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double y = 4;</code>
       *
       * <pre>
       * Coordinate Y
       * </pre>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>required double y = 4;</code>
       *
       * <pre>
       * Coordinate Y
       * </pre>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double y = 4;</code>
       *
       * <pre>
       * Coordinate Y
       * </pre>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:roah_rsbb_msgs.TabletBeacon)
    }

    static {
      defaultInstance = new TabletBeacon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:roah_rsbb_msgs.TabletBeacon)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roah_rsbb_msgs_TabletBeacon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_roah_rsbb_msgs_TabletBeacon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TabletBeacon.proto\022\016roah_rsbb_msgs\032\nTi" +
      "me.proto\"\235\001\n\014TabletBeacon\022\'\n\tlast_call\030\001" +
      " \002(\0132\024.roah_rsbb_msgs.Time\022&\n\010last_pos\030\002" +
      " \002(\0132\024.roah_rsbb_msgs.Time\022\t\n\001x\030\003 \002(\001\022\t\n" +
      "\001y\030\004 \002(\001\"&\n\010CompType\022\014\n\007COMP_ID\020\2124\022\014\n\010MS" +
      "G_TYPE\020#B.\n\030eu.rockin.roah_rsbb_msgsB\022Ta" +
      "bletBeaconProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          eu.rockin.roah_rsbb_msgs.TimeProtos.getDescriptor(),
        }, assigner);
    internal_static_roah_rsbb_msgs_TabletBeacon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_roah_rsbb_msgs_TabletBeacon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_roah_rsbb_msgs_TabletBeacon_descriptor,
        new java.lang.String[] { "LastCall", "LastPos", "X", "Y", });
    eu.rockin.roah_rsbb_msgs.TimeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
